//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.18444
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

// Ursprünglicher Dateiname:
// Erstellungsdatum: 08.01.2015 10:13:33
namespace KrachConnect.DomainModelService
{
    
    /// <summary>
    /// Im Schema sind keine Kommentare für "DomainModelContext" vorhanden.
    /// </summary>
    public partial class DomainModelContext : global::System.Data.Services.Client.DataServiceContext
    {
        /// <summary>
        /// Initialisiert ein neues DomainModelContext-Objekt.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public DomainModelContext(global::System.Uri serviceRoot) : 
                base(serviceRoot, global::System.Data.Services.Common.DataServiceProtocolVersion.V3)
        {
            this.ResolveName = new global::System.Func<global::System.Type, string>(this.ResolveNameFromType);
            this.ResolveType = new global::System.Func<string, global::System.Type>(this.ResolveTypeFromName);
            this.OnContextCreated();
        }
        partial void OnContextCreated();
        /// <summary>
        /// Da sich der Namespace, der für diesen Dienstverweis in
        /// Visual Studio konfiguriert ist, von demjenigen unterscheidet,
        /// der im Server-Schema angegeben ist, verwenden Sie Typemapper,
        /// um Zuordnungen zwischen den beiden vorzunehmen.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected global::System.Type ResolveTypeFromName(string typeName)
        {
            if (typeName.StartsWith("OpenResKit.DomainModel", global::System.StringComparison.Ordinal))
            {
                return this.GetType().Assembly.GetType(string.Concat("KrachConnect.DomainModelService", typeName.Substring(22)), false);
            }
            return null;
        }
        /// <summary>
        /// Da sich der Namespace, der für diesen Dienstverweis in
        /// Visual Studio konfiguriert ist, von demjenigen unterscheidet,
        /// der im Server-Schema angegeben ist, verwenden Sie Typemapper,
        /// um Zuordnungen zwischen den beiden vorzunehmen.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected string ResolveNameFromType(global::System.Type clientType)
        {
            if (clientType.Namespace.Equals("KrachConnect.DomainModelService", global::System.StringComparison.Ordinal))
            {
                return string.Concat("OpenResKit.DomainModel.", clientType.Name);
            }
            return null;
        }
        /// <summary>
        /// Im Schema sind keine Kommentare für "NoiseMeasurements" vorhanden.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<NoiseMeasurement> NoiseMeasurements
        {
            get
            {
                if ((this._NoiseMeasurements == null))
                {
                    this._NoiseMeasurements = base.CreateQuery<NoiseMeasurement>("NoiseMeasurements");
                }
                return this._NoiseMeasurements;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<NoiseMeasurement> _NoiseMeasurements;
        /// <summary>
        /// Im Schema sind keine Kommentare für "MeasuringMethods" vorhanden.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<MeasuringMethod> MeasuringMethods
        {
            get
            {
                if ((this._MeasuringMethods == null))
                {
                    this._MeasuringMethods = base.CreateQuery<MeasuringMethod>("MeasuringMethods");
                }
                return this._MeasuringMethods;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<MeasuringMethod> _MeasuringMethods;
        /// <summary>
        /// Im Schema sind keine Kommentare für "MeasuringPoints" vorhanden.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<MeasuringPoint> MeasuringPoints
        {
            get
            {
                if ((this._MeasuringPoints == null))
                {
                    this._MeasuringPoints = base.CreateQuery<MeasuringPoint>("MeasuringPoints");
                }
                return this._MeasuringPoints;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<MeasuringPoint> _MeasuringPoints;
        /// <summary>
        /// Im Schema sind keine Kommentare für "NoiseMapPositions" vorhanden.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<NoiseMapPosition> NoiseMapPositions
        {
            get
            {
                if ((this._NoiseMapPositions == null))
                {
                    this._NoiseMapPositions = base.CreateQuery<NoiseMapPosition>("NoiseMapPositions");
                }
                return this._NoiseMapPositions;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<NoiseMapPosition> _NoiseMapPositions;
        /// <summary>
        /// Im Schema sind keine Kommentare für "NoiseMaps" vorhanden.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<NoiseMap> NoiseMaps
        {
            get
            {
                if ((this._NoiseMaps == null))
                {
                    this._NoiseMaps = base.CreateQuery<NoiseMap>("NoiseMaps");
                }
                return this._NoiseMaps;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<NoiseMap> _NoiseMaps;
        /// <summary>
        /// Im Schema sind keine Kommentare für "Files" vorhanden.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<File> Files
        {
            get
            {
                if ((this._Files == null))
                {
                    this._Files = base.CreateQuery<File>("Files");
                }
                return this._Files;
            }
        }

        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<File> _Files;
        /// <summary>
        /// Im Schema sind keine Kommentare für "NoiseMeasurements" vorhanden.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToNoiseMeasurements(NoiseMeasurement noiseMeasurement)
        {
            base.AddObject("NoiseMeasurements", noiseMeasurement);
        }
        /// <summary>
        /// Im Schema sind keine Kommentare für "MeasuringMethods" vorhanden.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToMeasuringMethods(MeasuringMethod measuringMethod)
        {
            base.AddObject("MeasuringMethods", measuringMethod);
        }
        /// <summary>
        /// Im Schema sind keine Kommentare für "MeasuringPoints" vorhanden.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToMeasuringPoints(MeasuringPoint measuringPoint)
        {
            base.AddObject("MeasuringPoints", measuringPoint);
        }
        /// <summary>
        /// Im Schema sind keine Kommentare für "NoiseMapPositions" vorhanden.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToNoiseMapPositions(NoiseMapPosition noiseMapPosition)
        {
            base.AddObject("NoiseMapPositions", noiseMapPosition);
        }
        /// <summary>
        /// Im Schema sind keine Kommentare für "NoiseMaps" vorhanden.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToNoiseMaps(NoiseMap noiseMap)
        {
            base.AddObject("NoiseMaps", noiseMap);
        }
        /// <summary>
        /// Im Schema sind keine Kommentare für "Files" vorhanden.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToFiles(File file)
        {
            base.AddObject("Files", file);
        }
    }
    /// <summary>
    /// Im Schema sind keine Kommentare für "OpenResKit.DomainModel.NoiseMeasurement" vorhanden.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("NoiseMeasurements")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Id")]
    public partial class NoiseMeasurement : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Erstellt ein neues NoiseMeasurement-Objekt.
        /// </summary>
        /// <param name="ID">Anfangswert von Id.</param>
        /// <param name="measurementDate">Anfangswert von MeasurementDate.</param>
        /// <param name="minValue">Anfangswert von MinValue.</param>
        /// <param name="maxValue">Anfangswert von MaxValue.</param>
        /// <param name="averageValue">Anfangswert von AverageValue.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static NoiseMeasurement CreateNoiseMeasurement(int ID, global::System.DateTime measurementDate, float minValue, float maxValue, float averageValue)
        {
            NoiseMeasurement noiseMeasurement = new NoiseMeasurement();
            noiseMeasurement.Id = ID;
            noiseMeasurement.MeasurementDate = measurementDate;
            noiseMeasurement.MinValue = minValue;
            noiseMeasurement.MaxValue = maxValue;
            noiseMeasurement.AverageValue = averageValue;
            return noiseMeasurement;
        }
        /// <summary>
        /// Im Schema sind keine Kommentare für die Eigenschaft "Id" vorhanden.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// Im Schema sind keine Kommentare für die Eigenschaft "MeasurementDate" vorhanden.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.DateTime MeasurementDate
        {
            get
            {
                return this._MeasurementDate;
            }
            set
            {
                this.OnMeasurementDateChanging(value);
                this._MeasurementDate = value;
                this.OnMeasurementDateChanged();
                this.OnPropertyChanged("MeasurementDate");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.DateTime _MeasurementDate;
        partial void OnMeasurementDateChanging(global::System.DateTime value);
        partial void OnMeasurementDateChanged();
        /// <summary>
        /// Im Schema sind keine Kommentare für die Eigenschaft "MinValue" vorhanden.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public float MinValue
        {
            get
            {
                return this._MinValue;
            }
            set
            {
                this.OnMinValueChanging(value);
                this._MinValue = value;
                this.OnMinValueChanged();
                this.OnPropertyChanged("MinValue");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private float _MinValue;
        partial void OnMinValueChanging(float value);
        partial void OnMinValueChanged();
        /// <summary>
        /// Im Schema sind keine Kommentare für die Eigenschaft "MaxValue" vorhanden.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public float MaxValue
        {
            get
            {
                return this._MaxValue;
            }
            set
            {
                this.OnMaxValueChanging(value);
                this._MaxValue = value;
                this.OnMaxValueChanged();
                this.OnPropertyChanged("MaxValue");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private float _MaxValue;
        partial void OnMaxValueChanging(float value);
        partial void OnMaxValueChanged();
        /// <summary>
        /// Im Schema sind keine Kommentare für die Eigenschaft "AverageValue" vorhanden.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public float AverageValue
        {
            get
            {
                return this._AverageValue;
            }
            set
            {
                this.OnAverageValueChanging(value);
                this._AverageValue = value;
                this.OnAverageValueChanged();
                this.OnPropertyChanged("AverageValue");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private float _AverageValue;
        partial void OnAverageValueChanging(float value);
        partial void OnAverageValueChanged();
        /// <summary>
        /// Im Schema sind keine Kommentare für die Eigenschaft "Employee" vorhanden.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Employee
        {
            get
            {
                return this._Employee;
            }
            set
            {
                this.OnEmployeeChanging(value);
                this._Employee = value;
                this.OnEmployeeChanged();
                this.OnPropertyChanged("Employee");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Employee;
        partial void OnEmployeeChanging(string value);
        partial void OnEmployeeChanged();
        /// <summary>
        /// Im Schema sind keine Kommentare für die Eigenschaft "Comment" vorhanden.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Comment
        {
            get
            {
                return this._Comment;
            }
            set
            {
                this.OnCommentChanging(value);
                this._Comment = value;
                this.OnCommentChanged();
                this.OnPropertyChanged("Comment");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Comment;
        partial void OnCommentChanging(string value);
        partial void OnCommentChanged();
        /// <summary>
        /// Im Schema sind keine Kommentare für "Method" vorhanden.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public MeasuringMethod Method
        {
            get
            {
                return this._Method;
            }
            set
            {
                this._Method = value;
                this.OnPropertyChanged("Method");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private MeasuringMethod _Method;
        /// <summary>
        /// Im Schema sind keine Kommentare für "MeasuringPoint" vorhanden.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public MeasuringPoint MeasuringPoint
        {
            get
            {
                return this._MeasuringPoint;
            }
            set
            {
                this._MeasuringPoint = value;
                this.OnPropertyChanged("MeasuringPoint");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private MeasuringPoint _MeasuringPoint;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// Im Schema sind keine Kommentare für "OpenResKit.DomainModel.MeasuringMethod" vorhanden.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("MeasuringMethods")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Id")]
    public partial class MeasuringMethod : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Erstellt ein neues MeasuringMethod-Objekt.
        /// </summary>
        /// <param name="ID">Anfangswert von Id.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static MeasuringMethod CreateMeasuringMethod(int ID)
        {
            MeasuringMethod measuringMethod = new MeasuringMethod();
            measuringMethod.Id = ID;
            return measuringMethod;
        }
        /// <summary>
        /// Im Schema sind keine Kommentare für die Eigenschaft "Id" vorhanden.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// Im Schema sind keine Kommentare für die Eigenschaft "Name" vorhanden.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this._Name = value;
                this.OnNameChanged();
                this.OnPropertyChanged("Name");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// Im Schema sind keine Kommentare für die Eigenschaft "Description" vorhanden.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Description
        {
            get
            {
                return this._Description;
            }
            set
            {
                this.OnDescriptionChanging(value);
                this._Description = value;
                this.OnDescriptionChanged();
                this.OnPropertyChanged("Description");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Description;
        partial void OnDescriptionChanging(string value);
        partial void OnDescriptionChanged();
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// Im Schema sind keine Kommentare für "OpenResKit.DomainModel.MeasuringPoint" vorhanden.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("MeasuringPoints")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Id")]
    public partial class MeasuringPoint : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Erstellt ein neues MeasuringPoint-Objekt.
        /// </summary>
        /// <param name="ID">Anfangswert von Id.</param>
        /// <param name="greenValue">Anfangswert von GreenValue.</param>
        /// <param name="yellowValue">Anfangswert von YellowValue.</param>
        /// <param name="redValue">Anfangswert von RedValue.</param>
        /// <param name="isArchived">Anfangswert von IsArchived.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static MeasuringPoint CreateMeasuringPoint(int ID, float greenValue, float yellowValue, float redValue, bool isArchived)
        {
            MeasuringPoint measuringPoint = new MeasuringPoint();
            measuringPoint.Id = ID;
            measuringPoint.GreenValue = greenValue;
            measuringPoint.YellowValue = yellowValue;
            measuringPoint.RedValue = redValue;
            measuringPoint.IsArchived = isArchived;
            return measuringPoint;
        }
        /// <summary>
        /// Im Schema sind keine Kommentare für die Eigenschaft "Id" vorhanden.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// Im Schema sind keine Kommentare für die Eigenschaft "Name" vorhanden.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this._Name = value;
                this.OnNameChanged();
                this.OnPropertyChanged("Name");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// Im Schema sind keine Kommentare für die Eigenschaft "Barcode" vorhanden.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Barcode
        {
            get
            {
                return this._Barcode;
            }
            set
            {
                this.OnBarcodeChanging(value);
                this._Barcode = value;
                this.OnBarcodeChanged();
                this.OnPropertyChanged("Barcode");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Barcode;
        partial void OnBarcodeChanging(string value);
        partial void OnBarcodeChanged();
        /// <summary>
        /// Im Schema sind keine Kommentare für die Eigenschaft "Notes" vorhanden.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Notes
        {
            get
            {
                return this._Notes;
            }
            set
            {
                this.OnNotesChanging(value);
                this._Notes = value;
                this.OnNotesChanged();
                this.OnPropertyChanged("Notes");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Notes;
        partial void OnNotesChanging(string value);
        partial void OnNotesChanged();
        /// <summary>
        /// Im Schema sind keine Kommentare für die Eigenschaft "GreenValue" vorhanden.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public float GreenValue
        {
            get
            {
                return this._GreenValue;
            }
            set
            {
                this.OnGreenValueChanging(value);
                this._GreenValue = value;
                this.OnGreenValueChanged();
                this.OnPropertyChanged("GreenValue");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private float _GreenValue;
        partial void OnGreenValueChanging(float value);
        partial void OnGreenValueChanged();
        /// <summary>
        /// Im Schema sind keine Kommentare für die Eigenschaft "YellowValue" vorhanden.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public float YellowValue
        {
            get
            {
                return this._YellowValue;
            }
            set
            {
                this.OnYellowValueChanging(value);
                this._YellowValue = value;
                this.OnYellowValueChanged();
                this.OnPropertyChanged("YellowValue");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private float _YellowValue;
        partial void OnYellowValueChanging(float value);
        partial void OnYellowValueChanged();
        /// <summary>
        /// Im Schema sind keine Kommentare für die Eigenschaft "RedValue" vorhanden.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public float RedValue
        {
            get
            {
                return this._RedValue;
            }
            set
            {
                this.OnRedValueChanging(value);
                this._RedValue = value;
                this.OnRedValueChanged();
                this.OnPropertyChanged("RedValue");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private float _RedValue;
        partial void OnRedValueChanging(float value);
        partial void OnRedValueChanged();
        /// <summary>
        /// Im Schema sind keine Kommentare für die Eigenschaft "IsArchived" vorhanden.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public bool IsArchived
        {
            get
            {
                return this._IsArchived;
            }
            set
            {
                this.OnIsArchivedChanging(value);
                this._IsArchived = value;
                this.OnIsArchivedChanged();
                this.OnPropertyChanged("IsArchived");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private bool _IsArchived;
        partial void OnIsArchivedChanging(bool value);
        partial void OnIsArchivedChanged();
        /// <summary>
        /// Im Schema sind keine Kommentare für "Position" vorhanden.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public NoiseMapPosition Position
        {
            get
            {
                return this._Position;
            }
            set
            {
                this._Position = value;
                this.OnPropertyChanged("Position");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private NoiseMapPosition _Position;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// Im Schema sind keine Kommentare für "OpenResKit.DomainModel.NoiseMapPosition" vorhanden.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("NoiseMapPositions")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Id")]
    public partial class NoiseMapPosition : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Erstellt ein neues NoiseMapPosition-Objekt.
        /// </summary>
        /// <param name="ID">Anfangswert von Id.</param>
        /// <param name="xPosition">Anfangswert von XPosition.</param>
        /// <param name="yPosition">Anfangswert von YPosition.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static NoiseMapPosition CreateNoiseMapPosition(int ID, int xPosition, int yPosition)
        {
            NoiseMapPosition noiseMapPosition = new NoiseMapPosition();
            noiseMapPosition.Id = ID;
            noiseMapPosition.XPosition = xPosition;
            noiseMapPosition.YPosition = yPosition;
            return noiseMapPosition;
        }
        /// <summary>
        /// Im Schema sind keine Kommentare für die Eigenschaft "Id" vorhanden.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// Im Schema sind keine Kommentare für die Eigenschaft "XPosition" vorhanden.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int XPosition
        {
            get
            {
                return this._XPosition;
            }
            set
            {
                this.OnXPositionChanging(value);
                this._XPosition = value;
                this.OnXPositionChanged();
                this.OnPropertyChanged("XPosition");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _XPosition;
        partial void OnXPositionChanging(int value);
        partial void OnXPositionChanged();
        /// <summary>
        /// Im Schema sind keine Kommentare für die Eigenschaft "YPosition" vorhanden.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int YPosition
        {
            get
            {
                return this._YPosition;
            }
            set
            {
                this.OnYPositionChanging(value);
                this._YPosition = value;
                this.OnYPositionChanged();
                this.OnPropertyChanged("YPosition");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _YPosition;
        partial void OnYPositionChanging(int value);
        partial void OnYPositionChanged();
        /// <summary>
        /// Im Schema sind keine Kommentare für "NoiseMap" vorhanden.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public NoiseMap NoiseMap
        {
            get
            {
                return this._NoiseMap;
            }
            set
            {
                this._NoiseMap = value;
                this.OnPropertyChanged("NoiseMap");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private NoiseMap _NoiseMap;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// Im Schema sind keine Kommentare für "OpenResKit.DomainModel.NoiseMap" vorhanden.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("NoiseMaps")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Id")]
    public partial class NoiseMap : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Erstellt ein neues NoiseMap-Objekt.
        /// </summary>
        /// <param name="ID">Anfangswert von Id.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static NoiseMap CreateNoiseMap(int ID)
        {
            NoiseMap noiseMap = new NoiseMap();
            noiseMap.Id = ID;
            return noiseMap;
        }
        /// <summary>
        /// Im Schema sind keine Kommentare für die Eigenschaft "Id" vorhanden.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// Im Schema sind keine Kommentare für die Eigenschaft "Site" vorhanden.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Site
        {
            get
            {
                return this._Site;
            }
            set
            {
                this.OnSiteChanging(value);
                this._Site = value;
                this.OnSiteChanged();
                this.OnPropertyChanged("Site");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Site;
        partial void OnSiteChanging(string value);
        partial void OnSiteChanged();
        /// <summary>
        /// Im Schema sind keine Kommentare für die Eigenschaft "Building" vorhanden.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Building
        {
            get
            {
                return this._Building;
            }
            set
            {
                this.OnBuildingChanging(value);
                this._Building = value;
                this.OnBuildingChanged();
                this.OnPropertyChanged("Building");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Building;
        partial void OnBuildingChanging(string value);
        partial void OnBuildingChanged();
        /// <summary>
        /// Im Schema sind keine Kommentare für die Eigenschaft "Level" vorhanden.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Level
        {
            get
            {
                return this._Level;
            }
            set
            {
                this.OnLevelChanging(value);
                this._Level = value;
                this.OnLevelChanged();
                this.OnPropertyChanged("Level");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Level;
        partial void OnLevelChanging(string value);
        partial void OnLevelChanged();
        /// <summary>
        /// Im Schema sind keine Kommentare für "File" vorhanden.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public File File
        {
            get
            {
                return this._File;
            }
            set
            {
                this._File = value;
                this.OnPropertyChanged("File");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private File _File;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// Im Schema sind keine Kommentare für "OpenResKit.DomainModel.File" vorhanden.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("Files")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Id")]
    public partial class File : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Erstellt ein neues File-Objekt.
        /// </summary>
        /// <param name="ID">Anfangswert von Id.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static File CreateFile(int ID)
        {
            File file = new File();
            file.Id = ID;
            return file;
        }
        /// <summary>
        /// Im Schema sind keine Kommentare für die Eigenschaft "Id" vorhanden.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// Im Schema sind keine Kommentare für die Eigenschaft "BinarySource" vorhanden.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public byte[] BinarySource
        {
            get
            {
                if ((this._BinarySource != null))
                {
                    return ((byte[])(this._BinarySource.Clone()));
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.OnBinarySourceChanging(value);
                this._BinarySource = value;
                this.OnBinarySourceChanged();
                this.OnPropertyChanged("BinarySource");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private byte[] _BinarySource;
        partial void OnBinarySourceChanging(byte[] value);
        partial void OnBinarySourceChanged();
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
}
