//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Original file name:
// Generation date: 07.01.2015 14:12:18
namespace KrachConnect.DomainModelService
{
    
    /// <summary>
    /// There are no comments for DomainModelContext in the schema.
    /// </summary>
    public partial class DomainModelContext : global::System.Data.Services.Client.DataServiceContext
    {
        /// <summary>
        /// Initialize a new DomainModelContext object.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public DomainModelContext(global::System.Uri serviceRoot) : 
                base(serviceRoot, global::System.Data.Services.Common.DataServiceProtocolVersion.V3)
        {
            this.ResolveName = new global::System.Func<global::System.Type, string>(this.ResolveNameFromType);
            this.ResolveType = new global::System.Func<string, global::System.Type>(this.ResolveTypeFromName);
            this.OnContextCreated();
            this.Format.LoadServiceModel = GeneratedEdmModel.GetInstance;
        }
        partial void OnContextCreated();
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected global::System.Type ResolveTypeFromName(string typeName)
        {
            global::System.Type resolvedType = this.DefaultResolveType(typeName, "OpenResKit.DomainModel", "KrachConnect.DomainModelService");
            if ((resolvedType != null))
            {
                return resolvedType;
            }
            return null;
        }
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected string ResolveNameFromType(global::System.Type clientType)
        {
            if (clientType.Namespace.Equals("KrachConnect.DomainModelService", global::System.StringComparison.Ordinal))
            {
                return string.Concat("OpenResKit.DomainModel.", clientType.Name);
            }
            return null;
        }
        /// <summary>
        /// There are no comments for NoiseMeasurements in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<NoiseMeasurement> NoiseMeasurements
        {
            get
            {
                if ((this._NoiseMeasurements == null))
                {
                    this._NoiseMeasurements = base.CreateQuery<NoiseMeasurement>("NoiseMeasurements");
                }
                return this._NoiseMeasurements;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<NoiseMeasurement> _NoiseMeasurements;
        /// <summary>
        /// There are no comments for MeasuringMethods in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<MeasuringMethod> MeasuringMethods
        {
            get
            {
                if ((this._MeasuringMethods == null))
                {
                    this._MeasuringMethods = base.CreateQuery<MeasuringMethod>("MeasuringMethods");
                }
                return this._MeasuringMethods;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<MeasuringMethod> _MeasuringMethods;
        /// <summary>
        /// There are no comments for MeasuringPoints in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<MeasuringPoint> MeasuringPoints
        {
            get
            {
                if ((this._MeasuringPoints == null))
                {
                    this._MeasuringPoints = base.CreateQuery<MeasuringPoint>("MeasuringPoints");
                }
                return this._MeasuringPoints;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<MeasuringPoint> _MeasuringPoints;
        /// <summary>
        /// There are no comments for NoiseMapPositions in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<NoiseMapPosition> NoiseMapPositions
        {
            get
            {
                if ((this._NoiseMapPositions == null))
                {
                    this._NoiseMapPositions = base.CreateQuery<NoiseMapPosition>("NoiseMapPositions");
                }
                return this._NoiseMapPositions;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<NoiseMapPosition> _NoiseMapPositions;
        /// <summary>
        /// There are no comments for NoiseMaps in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<NoiseMap> NoiseMaps
        {
            get
            {
                if ((this._NoiseMaps == null))
                {
                    this._NoiseMaps = base.CreateQuery<NoiseMap>("NoiseMaps");
                }
                return this._NoiseMaps;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<NoiseMap> _NoiseMaps;
        /// <summary>
        /// There are no comments for Files in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<File> Files
        {
            get
            {
                if ((this._Files == null))
                {
                    this._Files = base.CreateQuery<File>("Files");
                }
                return this._Files;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<File> _Files;
        /// <summary>
        /// There are no comments for NoiseMeasurements in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToNoiseMeasurements(NoiseMeasurement noiseMeasurement)
        {
            base.AddObject("NoiseMeasurements", noiseMeasurement);
        }
        /// <summary>
        /// There are no comments for MeasuringMethods in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToMeasuringMethods(MeasuringMethod measuringMethod)
        {
            base.AddObject("MeasuringMethods", measuringMethod);
        }
        /// <summary>
        /// There are no comments for MeasuringPoints in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToMeasuringPoints(MeasuringPoint measuringPoint)
        {
            base.AddObject("MeasuringPoints", measuringPoint);
        }
        /// <summary>
        /// There are no comments for NoiseMapPositions in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToNoiseMapPositions(NoiseMapPosition noiseMapPosition)
        {
            base.AddObject("NoiseMapPositions", noiseMapPosition);
        }
        /// <summary>
        /// There are no comments for NoiseMaps in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToNoiseMaps(NoiseMap noiseMap)
        {
            base.AddObject("NoiseMaps", noiseMap);
        }
        /// <summary>
        /// There are no comments for Files in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToFiles(File file)
        {
            base.AddObject("Files", file);
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private abstract class GeneratedEdmModel
        {
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static global::Microsoft.Data.Edm.IEdmModel ParsedModel = LoadModelFromString();
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private const string ModelPart0 = "<edmx:Edmx Version=\"1.0\" xmlns:edmx=\"http://schemas.microsoft.com/ado/2007/06/edm" +
                "x\"><edmx:DataServices m:DataServiceVersion=\"1.0\" m:MaxDataServiceVersion=\"3.0\" x" +
                "mlns:m=\"http://schemas.microsoft.com/ado/2007/08/dataservices/metadata\"><Schema " +
                "Namespace=\"OpenResKit.DomainModel\" xmlns=\"http://schemas.microsoft.com/ado/2009/" +
                "11/edm\"><EntityType Name=\"NoiseMeasurement\"><Key><PropertyRef Name=\"Id\" /></Key>" +
                "<Property Name=\"Id\" Type=\"Edm.Int32\" Nullable=\"false\" p6:StoreGeneratedPattern=\"" +
                "Identity\" xmlns:p6=\"http://schemas.microsoft.com/ado/2009/02/edm/annotation\" /><" +
                "Property Name=\"MeasurementDate\" Type=\"Edm.DateTime\" Nullable=\"false\" /><Property" +
                " Name=\"MinValue\" Type=\"Edm.Single\" Nullable=\"false\" /><Property Name=\"MaxValue\" " +
                "Type=\"Edm.Single\" Nullable=\"false\" /><Property Name=\"AverageValue\" Type=\"Edm.Sin" +
                "gle\" Nullable=\"false\" /><Property Name=\"Employee\" Type=\"Edm.String\" MaxLength=\"M" +
                "ax\" FixedLength=\"false\" Unicode=\"true\" /><Property Name=\"Comment\" Type=\"Edm.Stri" +
                "ng\" MaxLength=\"Max\" FixedLength=\"false\" Unicode=\"true\" /><NavigationProperty Nam" +
                "e=\"Method\" Relationship=\"OpenResKit.DomainModel.NoiseMeasurement_Method\" ToRole=" +
                "\"NoiseMeasurement_Method_Target\" FromRole=\"NoiseMeasurement_Method_Source\" /><Na" +
                "vigationProperty Name=\"MeasuringPoint\" Relationship=\"OpenResKit.DomainModel.Nois" +
                "eMeasurement_MeasuringPoint\" ToRole=\"NoiseMeasurement_MeasuringPoint_Target\" Fro" +
                "mRole=\"NoiseMeasurement_MeasuringPoint_Source\" /></EntityType><EntityType Name=\"" +
                "MeasuringMethod\"><Key><PropertyRef Name=\"Id\" /></Key><Property Name=\"Id\" Type=\"E" +
                "dm.Int32\" Nullable=\"false\" p6:StoreGeneratedPattern=\"Identity\" xmlns:p6=\"http://" +
                "schemas.microsoft.com/ado/2009/02/edm/annotation\" /><Property Name=\"Name\" Type=\"" +
                "Edm.String\" MaxLength=\"Max\" FixedLength=\"false\" Unicode=\"true\" /><Property Name=" +
                "\"Description\" Type=\"Edm.String\" MaxLength=\"Max\" FixedLength=\"false\" Unicode=\"tru" +
                "e\" /></EntityType><EntityType Name=\"MeasuringPoint\"><Key><PropertyRef Name=\"Id\" " +
                "/></Key><Property Name=\"Id\" Type=\"Edm.Int32\" Nullable=\"false\" p6:StoreGeneratedP" +
                "attern=\"Identity\" xmlns:p6=\"http://schemas.microsoft.com/ado/2009/02/edm/annotat" +
                "ion\" /><Property Name=\"Name\" Type=\"Edm.String\" MaxLength=\"Max\" FixedLength=\"fals" +
                "e\" Unicode=\"true\" /><Property Name=\"Barcode\" Type=\"Edm.String\" MaxLength=\"Max\" F" +
                "ixedLength=\"false\" Unicode=\"true\" /><Property Name=\"Notes\" Type=\"Edm.String\" Max" +
                "Length=\"Max\" FixedLength=\"false\" Unicode=\"true\" /><Property Name=\"GreenValue\" Ty" +
                "pe=\"Edm.Single\" Nullable=\"false\" /><Property Name=\"YellowValue\" Type=\"Edm.Single" +
                "\" Nullable=\"false\" /><Property Name=\"RedValue\" Type=\"Edm.Single\" Nullable=\"false" +
                "\" /><Property Name=\"IsArchived\" Type=\"Edm.Boolean\" Nullable=\"false\" /><Navigatio" +
                "nProperty Name=\"Position\" Relationship=\"OpenResKit.DomainModel.MeasuringPoint_Po" +
                "sition\" ToRole=\"MeasuringPoint_Position_Target\" FromRole=\"MeasuringPoint_Positio" +
                "n_Source\" /></EntityType><EntityType Name=\"NoiseMapPosition\"><Key><PropertyRef N" +
                "ame=\"Id\" /></Key><Property Name=\"Id\" Type=\"Edm.Int32\" Nullable=\"false\" p6:StoreG" +
                "eneratedPattern=\"Identity\" xmlns:p6=\"http://schemas.microsoft.com/ado/2009/02/ed" +
                "m/annotation\" /><Property Name=\"XPosition\" Type=\"Edm.Int32\" Nullable=\"false\" /><" +
                "Property Name=\"YPosition\" Type=\"Edm.Int32\" Nullable=\"false\" /><NavigationPropert" +
                "y Name=\"NoiseMap\" Relationship=\"OpenResKit.DomainModel.NoiseMapPosition_NoiseMap" +
                "\" ToRole=\"NoiseMapPosition_NoiseMap_Target\" FromRole=\"NoiseMapPosition_NoiseMap_" +
                "Source\" /></EntityType><EntityType Name=\"NoiseMap\"><Key><PropertyRef Name=\"Id\" /" +
                "></Key><Property Name=\"Id\" Type=\"Edm.Int32\" Nullable=\"false\" p6:StoreGeneratedPa" +
                "ttern=\"Identity\" xmlns:p6=\"http://schemas.microsoft.com/ado/2009/02/edm/annotati" +
                "on\" /><Property Name=\"Site\" Type=\"Edm.String\" MaxLength=\"Max\" FixedLength=\"false" +
                "\" Unicode=\"true\" /><Property Name=\"Building\" Type=\"Edm.String\" MaxLength=\"Max\" F" +
                "ixedLength=\"false\" Unicode=\"true\" /><Property Name=\"Level\" Type=\"Edm.String\" Max" +
                "Length=\"Max\" FixedLength=\"false\" Unicode=\"true\" /><NavigationProperty Name=\"File" +
                "\" Relationship=\"OpenResKit.DomainModel.NoiseMap_File\" ToRole=\"NoiseMap_File_Targ" +
                "et\" FromRole=\"NoiseMap_File_Source\" /></EntityType><EntityType Name=\"File\"><Key>" +
                "<PropertyRef Name=\"Id\" /></Key><Property Name=\"Id\" Type=\"Edm.Int32\" Nullable=\"fa" +
                "lse\" p6:StoreGeneratedPattern=\"Identity\" xmlns:p6=\"http://schemas.microsoft.com/" +
                "ado/2009/02/edm/annotation\" /><Property Name=\"BinarySource\" Type=\"Edm.Binary\" Ma" +
                "xLength=\"Max\" FixedLength=\"false\" /></EntityType><Association Name=\"NoiseMeasure" +
                "ment_Method\"><End Type=\"OpenResKit.DomainModel.MeasuringMethod\" Role=\"NoiseMeasu" +
                "rement_Method_Target\" Multiplicity=\"0..1\" /><End Type=\"OpenResKit.DomainModel.No" +
                "iseMeasurement\" Role=\"NoiseMeasurement_Method_Source\" Multiplicity=\"*\" /></Assoc" +
                "iation><Association Name=\"NoiseMeasurement_MeasuringPoint\"><End Type=\"OpenResKit" +
                ".DomainModel.MeasuringPoint\" Role=\"NoiseMeasurement_MeasuringPoint_Target\" Multi" +
                "plicity=\"0..1\" /><End Type=\"OpenResKit.DomainModel.NoiseMeasurement\" Role=\"Noise" +
                "Measurement_MeasuringPoint_Source\" Multiplicity=\"*\" /></Association><Association" +
                " Name=\"MeasuringPoint_Position\"><End Type=\"OpenResKit.DomainModel.MeasuringPoint" +
                "\" Role=\"MeasuringPoint_Position_Source\" Multiplicity=\"0..1\" /><End Type=\"OpenRes" +
                "Kit.DomainModel.NoiseMapPosition\" Role=\"MeasuringPoint_Position_Target\" Multipli" +
                "city=\"0..1\"><OnDelete Action=\"Cascade\" /></End></Association><Association Name=\"" +
                "NoiseMapPosition_NoiseMap\"><End Type=\"OpenResKit.DomainModel.NoiseMap\" Role=\"Noi" +
                "seMapPosition_NoiseMap_Target\" Multiplicity=\"0..1\" /><End Type=\"OpenResKit.Domai" +
                "nModel.NoiseMapPosition\" Role=\"NoiseMapPosition_NoiseMap_Source\" Multiplicity=\"*" +
                "\" /></Association><Association Name=\"NoiseMap_File\"><End Type=\"OpenResKit.Domain" +
                "Model.File\" Role=\"NoiseMap_File_Target\" Multiplicity=\"0..1\"><OnDelete Action=\"Ca" +
                "scade\" /></End><End Type=\"OpenResKit.DomainModel.NoiseMap\" Role=\"NoiseMap_File_S" +
                "ource\" Multiplicity=\"0..1\" /></Association><EntityContainer Name=\"DomainModelCon" +
                "text\" m:IsDefaultEntityContainer=\"true\"><EntitySet Name=\"NoiseMeasurements\" Enti" +
                "tyType=\"OpenResKit.DomainModel.NoiseMeasurement\" /><EntitySet Name=\"MeasuringMet" +
                "hods\" EntityType=\"OpenResKit.DomainModel.MeasuringMethod\" /><EntitySet Name=\"Mea" +
                "suringPoints\" EntityType=\"OpenResKit.DomainModel.MeasuringPoint\" /><EntitySet Na" +
                "me=\"NoiseMapPositions\" EntityType=\"OpenResKit.DomainModel.NoiseMapPosition\" /><E" +
                "ntitySet Name=\"NoiseMaps\" EntityType=\"OpenResKit.DomainModel.NoiseMap\" /><Entity" +
                "Set Name=\"Files\" EntityType=\"OpenResKit.DomainModel.File\" /><AssociationSet Name" +
                "=\"NoiseMeasurement_Method\" Association=\"OpenResKit.DomainModel.NoiseMeasurement_" +
                "Method\"><End Role=\"NoiseMeasurement_Method_Source\" EntitySet=\"NoiseMeasurements\"" +
                " /><End Role=\"NoiseMeasurement_Method_Target\" EntitySet=\"MeasuringMethods\" /></A" +
                "ssociationSet><AssociationSet Name=\"NoiseMeasurement_MeasuringPoint\" Association" +
                "=\"OpenResKit.DomainModel.NoiseMeasurement_MeasuringPoint\"><End Role=\"NoiseMeasur" +
                "ement_MeasuringPoint_Source\" EntitySet=\"NoiseMeasurements\" /><End Role=\"NoiseMea" +
                "surement_MeasuringPoint_Target\" EntitySet=\"MeasuringPoints\" /></AssociationSet><" +
                "AssociationSet Name=\"MeasuringPoint_Position\" Association=\"OpenResKit.DomainMode" +
                "l.MeasuringPoint_Position\"><End Role=\"MeasuringPoint_Position_Source\" EntitySet=" +
                "\"MeasuringPoints\" /><End Role=\"MeasuringPoint_Position_Target\" EntitySet=\"NoiseM" +
                "apPositions\" /></AssociationSet><AssociationSet Name=\"NoiseMapPosition_NoiseMap\"" +
                " Association=\"OpenResKit.DomainModel.NoiseMapPosition_NoiseMap\"><End Role=\"Noise" +
                "MapPosition_NoiseMap_Source\" EntitySet=\"NoiseMapPositions\" /><End Role=\"NoiseMap" +
                "Position_NoiseMap_Target\" EntitySet=\"NoiseMaps\" /></Associa";
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private const string ModelPart1 = @"tionSet><AssociationSet Name=""NoiseMap_File"" Association=""OpenResKit.DomainModel.NoiseMap_File""><End Role=""NoiseMap_File_Source"" EntitySet=""NoiseMaps"" /><End Role=""NoiseMap_File_Target"" EntitySet=""Files"" /></AssociationSet></EntityContainer></Schema></edmx:DataServices></edmx:Edmx>";
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static string GetConcatenatedEdmxString()
            {
                return string.Concat(ModelPart0, ModelPart1);
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            public static global::Microsoft.Data.Edm.IEdmModel GetInstance()
            {
                return ParsedModel;
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static global::Microsoft.Data.Edm.IEdmModel LoadModelFromString()
            {
                string edmxToParse = GetConcatenatedEdmxString();
                global::System.Xml.XmlReader reader = CreateXmlReader(edmxToParse);
                try
                {
                    return global::Microsoft.Data.Edm.Csdl.EdmxReader.Parse(reader);
                }
                finally
                {
                    ((global::System.IDisposable)(reader)).Dispose();
                }
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static global::System.Xml.XmlReader CreateXmlReader(string edmxToParse)
            {
                return global::System.Xml.XmlReader.Create(new global::System.IO.StringReader(edmxToParse));
            }
        }
    }
    /// <summary>
    /// There are no comments for OpenResKit.DomainModel.NoiseMeasurement in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("NoiseMeasurements")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Id")]
    public partial class NoiseMeasurement : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new NoiseMeasurement object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        /// <param name="measurementDate">Initial value of MeasurementDate.</param>
        /// <param name="minValue">Initial value of MinValue.</param>
        /// <param name="maxValue">Initial value of MaxValue.</param>
        /// <param name="averageValue">Initial value of AverageValue.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static NoiseMeasurement CreateNoiseMeasurement(int ID, global::System.DateTime measurementDate, float minValue, float maxValue, float averageValue)
        {
            NoiseMeasurement noiseMeasurement = new NoiseMeasurement();
            noiseMeasurement.Id = ID;
            noiseMeasurement.MeasurementDate = measurementDate;
            noiseMeasurement.MinValue = minValue;
            noiseMeasurement.MaxValue = maxValue;
            noiseMeasurement.AverageValue = averageValue;
            return noiseMeasurement;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property MeasurementDate in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.DateTime MeasurementDate
        {
            get
            {
                return this._MeasurementDate;
            }
            set
            {
                this.OnMeasurementDateChanging(value);
                this._MeasurementDate = value;
                this.OnMeasurementDateChanged();
                this.OnPropertyChanged("MeasurementDate");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.DateTime _MeasurementDate;
        partial void OnMeasurementDateChanging(global::System.DateTime value);
        partial void OnMeasurementDateChanged();
        /// <summary>
        /// There are no comments for Property MinValue in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public float MinValue
        {
            get
            {
                return this._MinValue;
            }
            set
            {
                this.OnMinValueChanging(value);
                this._MinValue = value;
                this.OnMinValueChanged();
                this.OnPropertyChanged("MinValue");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private float _MinValue;
        partial void OnMinValueChanging(float value);
        partial void OnMinValueChanged();
        /// <summary>
        /// There are no comments for Property MaxValue in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public float MaxValue
        {
            get
            {
                return this._MaxValue;
            }
            set
            {
                this.OnMaxValueChanging(value);
                this._MaxValue = value;
                this.OnMaxValueChanged();
                this.OnPropertyChanged("MaxValue");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private float _MaxValue;
        partial void OnMaxValueChanging(float value);
        partial void OnMaxValueChanged();
        /// <summary>
        /// There are no comments for Property AverageValue in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public float AverageValue
        {
            get
            {
                return this._AverageValue;
            }
            set
            {
                this.OnAverageValueChanging(value);
                this._AverageValue = value;
                this.OnAverageValueChanged();
                this.OnPropertyChanged("AverageValue");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private float _AverageValue;
        partial void OnAverageValueChanging(float value);
        partial void OnAverageValueChanged();
        /// <summary>
        /// There are no comments for Property Employee in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Employee
        {
            get
            {
                return this._Employee;
            }
            set
            {
                this.OnEmployeeChanging(value);
                this._Employee = value;
                this.OnEmployeeChanged();
                this.OnPropertyChanged("Employee");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Employee;
        partial void OnEmployeeChanging(string value);
        partial void OnEmployeeChanged();
        /// <summary>
        /// There are no comments for Property Comment in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Comment
        {
            get
            {
                return this._Comment;
            }
            set
            {
                this.OnCommentChanging(value);
                this._Comment = value;
                this.OnCommentChanged();
                this.OnPropertyChanged("Comment");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Comment;
        partial void OnCommentChanging(string value);
        partial void OnCommentChanged();
        /// <summary>
        /// There are no comments for Method in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public MeasuringMethod Method
        {
            get
            {
                return this._Method;
            }
            set
            {
                this._Method = value;
                this.OnPropertyChanged("Method");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private MeasuringMethod _Method;
        /// <summary>
        /// There are no comments for MeasuringPoint in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public MeasuringPoint MeasuringPoint
        {
            get
            {
                return this._MeasuringPoint;
            }
            set
            {
                this._MeasuringPoint = value;
                this.OnPropertyChanged("MeasuringPoint");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private MeasuringPoint _MeasuringPoint;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for OpenResKit.DomainModel.MeasuringMethod in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("MeasuringMethods")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Id")]
    public partial class MeasuringMethod : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new MeasuringMethod object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static MeasuringMethod CreateMeasuringMethod(int ID)
        {
            MeasuringMethod measuringMethod = new MeasuringMethod();
            measuringMethod.Id = ID;
            return measuringMethod;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this._Name = value;
                this.OnNameChanged();
                this.OnPropertyChanged("Name");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// There are no comments for Property Description in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Description
        {
            get
            {
                return this._Description;
            }
            set
            {
                this.OnDescriptionChanging(value);
                this._Description = value;
                this.OnDescriptionChanged();
                this.OnPropertyChanged("Description");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Description;
        partial void OnDescriptionChanging(string value);
        partial void OnDescriptionChanged();
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for OpenResKit.DomainModel.MeasuringPoint in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("MeasuringPoints")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Id")]
    public partial class MeasuringPoint : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new MeasuringPoint object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        /// <param name="greenValue">Initial value of GreenValue.</param>
        /// <param name="yellowValue">Initial value of YellowValue.</param>
        /// <param name="redValue">Initial value of RedValue.</param>
        /// <param name="isArchived">Initial value of IsArchived.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static MeasuringPoint CreateMeasuringPoint(int ID, float greenValue, float yellowValue, float redValue, bool isArchived)
        {
            MeasuringPoint measuringPoint = new MeasuringPoint();
            measuringPoint.Id = ID;
            measuringPoint.GreenValue = greenValue;
            measuringPoint.YellowValue = yellowValue;
            measuringPoint.RedValue = redValue;
            measuringPoint.IsArchived = isArchived;
            return measuringPoint;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this._Name = value;
                this.OnNameChanged();
                this.OnPropertyChanged("Name");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// There are no comments for Property Barcode in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Barcode
        {
            get
            {
                return this._Barcode;
            }
            set
            {
                this.OnBarcodeChanging(value);
                this._Barcode = value;
                this.OnBarcodeChanged();
                this.OnPropertyChanged("Barcode");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Barcode;
        partial void OnBarcodeChanging(string value);
        partial void OnBarcodeChanged();
        /// <summary>
        /// There are no comments for Property Notes in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Notes
        {
            get
            {
                return this._Notes;
            }
            set
            {
                this.OnNotesChanging(value);
                this._Notes = value;
                this.OnNotesChanged();
                this.OnPropertyChanged("Notes");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Notes;
        partial void OnNotesChanging(string value);
        partial void OnNotesChanged();
        /// <summary>
        /// There are no comments for Property GreenValue in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public float GreenValue
        {
            get
            {
                return this._GreenValue;
            }
            set
            {
                this.OnGreenValueChanging(value);
                this._GreenValue = value;
                this.OnGreenValueChanged();
                this.OnPropertyChanged("GreenValue");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private float _GreenValue;
        partial void OnGreenValueChanging(float value);
        partial void OnGreenValueChanged();
        /// <summary>
        /// There are no comments for Property YellowValue in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public float YellowValue
        {
            get
            {
                return this._YellowValue;
            }
            set
            {
                this.OnYellowValueChanging(value);
                this._YellowValue = value;
                this.OnYellowValueChanged();
                this.OnPropertyChanged("YellowValue");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private float _YellowValue;
        partial void OnYellowValueChanging(float value);
        partial void OnYellowValueChanged();
        /// <summary>
        /// There are no comments for Property RedValue in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public float RedValue
        {
            get
            {
                return this._RedValue;
            }
            set
            {
                this.OnRedValueChanging(value);
                this._RedValue = value;
                this.OnRedValueChanged();
                this.OnPropertyChanged("RedValue");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private float _RedValue;
        partial void OnRedValueChanging(float value);
        partial void OnRedValueChanged();
        /// <summary>
        /// There are no comments for Property IsArchived in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public bool IsArchived
        {
            get
            {
                return this._IsArchived;
            }
            set
            {
                this.OnIsArchivedChanging(value);
                this._IsArchived = value;
                this.OnIsArchivedChanged();
                this.OnPropertyChanged("IsArchived");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private bool _IsArchived;
        partial void OnIsArchivedChanging(bool value);
        partial void OnIsArchivedChanged();
        /// <summary>
        /// There are no comments for Position in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public NoiseMapPosition Position
        {
            get
            {
                return this._Position;
            }
            set
            {
                this._Position = value;
                this.OnPropertyChanged("Position");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private NoiseMapPosition _Position;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for OpenResKit.DomainModel.NoiseMapPosition in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("NoiseMapPositions")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Id")]
    public partial class NoiseMapPosition : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new NoiseMapPosition object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        /// <param name="xPosition">Initial value of XPosition.</param>
        /// <param name="yPosition">Initial value of YPosition.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static NoiseMapPosition CreateNoiseMapPosition(int ID, int xPosition, int yPosition)
        {
            NoiseMapPosition noiseMapPosition = new NoiseMapPosition();
            noiseMapPosition.Id = ID;
            noiseMapPosition.XPosition = xPosition;
            noiseMapPosition.YPosition = yPosition;
            return noiseMapPosition;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property XPosition in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int XPosition
        {
            get
            {
                return this._XPosition;
            }
            set
            {
                this.OnXPositionChanging(value);
                this._XPosition = value;
                this.OnXPositionChanged();
                this.OnPropertyChanged("XPosition");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _XPosition;
        partial void OnXPositionChanging(int value);
        partial void OnXPositionChanged();
        /// <summary>
        /// There are no comments for Property YPosition in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int YPosition
        {
            get
            {
                return this._YPosition;
            }
            set
            {
                this.OnYPositionChanging(value);
                this._YPosition = value;
                this.OnYPositionChanged();
                this.OnPropertyChanged("YPosition");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _YPosition;
        partial void OnYPositionChanging(int value);
        partial void OnYPositionChanged();
        /// <summary>
        /// There are no comments for NoiseMap in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public NoiseMap NoiseMap
        {
            get
            {
                return this._NoiseMap;
            }
            set
            {
                this._NoiseMap = value;
                this.OnPropertyChanged("NoiseMap");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private NoiseMap _NoiseMap;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for OpenResKit.DomainModel.NoiseMap in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("NoiseMaps")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Id")]
    public partial class NoiseMap : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new NoiseMap object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static NoiseMap CreateNoiseMap(int ID)
        {
            NoiseMap noiseMap = new NoiseMap();
            noiseMap.Id = ID;
            return noiseMap;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property Site in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Site
        {
            get
            {
                return this._Site;
            }
            set
            {
                this.OnSiteChanging(value);
                this._Site = value;
                this.OnSiteChanged();
                this.OnPropertyChanged("Site");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Site;
        partial void OnSiteChanging(string value);
        partial void OnSiteChanged();
        /// <summary>
        /// There are no comments for Property Building in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Building
        {
            get
            {
                return this._Building;
            }
            set
            {
                this.OnBuildingChanging(value);
                this._Building = value;
                this.OnBuildingChanged();
                this.OnPropertyChanged("Building");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Building;
        partial void OnBuildingChanging(string value);
        partial void OnBuildingChanged();
        /// <summary>
        /// There are no comments for Property Level in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Level
        {
            get
            {
                return this._Level;
            }
            set
            {
                this.OnLevelChanging(value);
                this._Level = value;
                this.OnLevelChanged();
                this.OnPropertyChanged("Level");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Level;
        partial void OnLevelChanging(string value);
        partial void OnLevelChanged();
        /// <summary>
        /// There are no comments for File in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public File File
        {
            get
            {
                return this._File;
            }
            set
            {
                this._File = value;
                this.OnPropertyChanged("File");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private File _File;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for OpenResKit.DomainModel.File in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("Files")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Id")]
    public partial class File : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new File object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static File CreateFile(int ID)
        {
            File file = new File();
            file.Id = ID;
            return file;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property BinarySource in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public byte[] BinarySource
        {
            get
            {
                if ((this._BinarySource != null))
                {
                    return ((byte[])(this._BinarySource.Clone()));
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.OnBinarySourceChanging(value);
                this._BinarySource = value;
                this.OnBinarySourceChanged();
                this.OnPropertyChanged("BinarySource");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private byte[] _BinarySource;
        partial void OnBinarySourceChanging(byte[] value);
        partial void OnBinarySourceChanged();
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
}
